version: '3'

services:
  cache:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: always
    
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
    env_file:
      - .env.dev
      
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=qshing_db
      
volumes:
  redis_data:
  mongodb_data:
  postgres_data:
