name: CI - upload image to registry

on:
  push:
    branches:
      - main  # [test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch Bucket
        run: |
          API_URL=${{ secrets.OCI_BUCKET_URL }}
          OBJECT_NAME=$(curl -s "$API_URL" | jq -r '.objects[0].name')
          echo "OBJECT_NAME=$OBJECT_NAME" >> $GITHUB_ENV

      - name: Download AI model Object
        run: |
          if [ -z "$OBJECT_NAME" ]; then
            echo "No model objects found in the bucket."
            exit 1
          fi

          echo "Downloading model object from $OBJECT_NAME"
          DOWNLOAD_URL="${{ secrets.OCI_BUCKET_URL }}/$OBJECT_NAME"
          curl -o "src/qshing_server/service/model/best_acc_model.pt" "$DOWNLOAD_URL"

      - name: Verify Downloaded Model
        run: ls -lh src/qshing_server/service/model/
